import {
  User,
  UserCircle,
  Smiley,
  SmileyMeh,
  SmileyWink,
  Cat,
  Dog,
  Butterfly,
  Fish,
  Bird,
  Rabbit,
  Horse,
  Heart,
  Star,
  Sparkle,
  Lightning,
  Fire,
  Moon,
  Sun,
  CloudRain,
  Flower,
  Tree,
  Leaf,
  Rocket,
  Airplane,
  Bicycle,
  Car,
  Baseball,
  Basketball,
  Football,
  SoccerBall,
  GameController,
  Guitar,
  MusicNote,
  Palette,
  PaintBrush,
  BookOpen,
  GraduationCap,
  Trophy,
  Crown,
  DiamondsFour,
  Pizza,
  Cookie,
  IceCream,
  Cake,
} from '@phosphor-icons/react'

export const PRESET_AVATAR_ICONS = [
  { name: 'User', icon: User },
  { name: 'UserCircle', icon: UserCircle },
  { name: 'Smiley', icon: Smiley },
  { name: 'SmileyMeh', icon: SmileyMeh },
  { name: 'SmileyWink', icon: SmileyWink },
  { name: 'Cat', icon: Cat },
  { name: 'Dog', icon: Dog },
  { name: 'Butterfly', icon: Butterfly },
  { name: 'Fish', icon: Fish },
  { name: 'Bird', icon: Bird },
  { name: 'Rabbit', icon: Rabbit },
  { name: 'Horse', icon: Horse },
  { name: 'Heart', icon: Heart },
  { name: 'Star', icon: Star },
  { name: 'Sparkle', icon: Sparkle },
  { name: 'Lightning', icon: Lightning },
  { name: 'Fire', icon: Fire },
  { name: 'Moon', icon: Moon },
  { name: 'Sun', icon: Sun },
  { name: 'CloudRain', icon: CloudRain },
  { name: 'Flower', icon: Flower },
  { name: 'Tree', icon: Tree },
  { name: 'Leaf', icon: Leaf },
  { name: 'Rocket', icon: Rocket },
  { name: 'Airplane', icon: Airplane },
  { name: 'Bicycle', icon: Bicycle },
  { name: 'Car', icon: Car },
  { name: 'Baseball', icon: Baseball },
  { name: 'Basketball', icon: Basketball },
  { name: 'Football', icon: Football },
  { name: 'SoccerBall', icon: SoccerBall },
  { name: 'GameController', icon: GameController },
  { name: 'Guitar', icon: Guitar },
  { name: 'MusicNote', icon: MusicNote },
  { name: 'Palette', icon: Palette },
  { name: 'PaintBrush', icon: PaintBrush },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Trophy', icon: Trophy },
  { name: 'Crown', icon: Crown },
  { name: 'DiamondsFour', icon: DiamondsFour },
  { name: 'Pizza', icon: Pizza },
  { name: 'Cookie', icon: Cookie },
  { name: 'IceCream', icon: IceCream },
  { name: 'Cake', icon: Cake },
] as const

export function getIconByName(iconName: string) {
  return PRESET_AVATAR_ICONS.find(icon => icon.name === iconName)?.icon
}
